services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: API_TOKEN
        value: "7509459901:AAHLb7yGn0YhHasiOVM8UdFioeZX0v9gnFY"  # Replace with your actual API token or use Render's secret management
    branch: main  # Make sure this is pointing to the correct branch
